services:
  # --- OBSERVABILITY STACK ---
  prometheus:
    image: prom/prometheus:latest
    container_name: adk_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    container_name: adk_loki
    user: "0"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: adk_grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
      - loki
      - prometheus

  # --- APPLICATION STACK ---
  db:
    image: postgres:15
    container_name: adk_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # --- The ONLY way to pass env vars to the DB service ---
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: adk_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: development
    container_name: adk_backend_api
    command: uvicorn app.main:socket_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/usr/src/app/app
      - ./backend/seed.py:/usr/src/app/seed.py
    ports:
      - "8000:8000"
    # --- THE FIX: Use ONLY the env_file directive ---
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: adk_frontend_ui
    command: npm run dev
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/components:/app/components
      - ./frontend/context:/app/context
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
    # --- THE FIX: Use ONLY the env_file directive ---
    env_file:
      - .env
    depends_on:
      - backend
    restart: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

volumes:
  postgres_data: