services:
  # ...
  db:
    image: postgres:15
    container_name: adk_postgres_db # Use the correct container name
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # The 'env_file' directive is the most reliable way to load these
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
# ... # ... (rest of db service is correct)
  redis:
    image: redis:7-alpine # ... (rest of redis service is correct)
  # ... (rest of the file is unchanged) ...

  backend:
    build: ./backend
    container_name: adk_backend_api
    command: uvicorn app.main:socket_app --host 0.0.0.0 --port 8000 --reload
    # --- THE FIX IS HERE ---
    # This volume mount ensures that your local code is mirrored inside the
    # container, including the vendored google_adk folder.
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: on-failure

# ... (rest of the file is unchanged) ...
  frontend:
    build: ./frontend # Simplified build context
    container_name: adk_frontend_ui
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: on-failure
volumes:
  postgres_data: